sudo: required
language: go
  - 1.9.x
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo docker run -p 5555:5555 -p 5556:5556 -d --name zest --rm jptmoore/zest:latest /app/zest/server.exe --secret-key-file example-server-key
script:
  - ./test/test-in-docker.sh
services:
  - docker